version: "3.7"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: on-failure
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=hellwest
    #   - MONGO_INITDB_ROOT_PASSWORD=hellwest
    #   - MONGO_INITDB_DATABASE=chat

  mongo-express:
    image: mongo-express:latest
    container_name: mgweb
    restart: on-failure
    ports:
      - "5433:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=chat
      - ME_CONFIG_BASICAUTH_PASSWORD=chat
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=hellwest
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=hellwest
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chat
      - ME_CONFIG_MONGODB_AUTH_USERNAME=hellwest
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=hellwest
    depends_on:
      - mongo

  app:
    build: .
    container_name: chat
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/app
    entrypoint:
      - yarn
      - start
    environment:
      - DB_HOST=mongo
      - DB_NAME=chat
    depends_on:
      - mongo

volumes:
  db:
