version: "3"
services:
  app:
    build: .
    container_name: chat
    ports:
      - "80:80"
      - "5432:5432"
    volumes:
      - .:/opt/app
      - reserved:/opt/app/node_modules/
    entrypoint:
      - npm
      - run
      - start
  postgres:
    image: postgres
    container_name: chat_db
    restart: on-failure
    volumes:
      - db:/opt/app/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
volumes:
  reserved:
  db: