version: "3"

services:
  postgres:
    image: postgres
    container_name: chat_db
    restart: on-failure
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat

  app:
    build: .
    container_name: chat
    ports:
      - "80:80"
      - "5432:5432"
    volumes:
      - .:/opt/app
    entrypoint:
      - yarn
      - start
    depends_on:
      - postgres

volumes:
  db:
